[package]
name = "kantyna-api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.3.1"
chrono = "0.4.24"
scraper = { version = "0.15.0", features = ["atomic"] }
serde = { version = "1.0.158", features = ["derive"] }
ureq = "2.6.2"
