openapi: 3.0.0
components:
  schemas:
    MenuVec:
      type: array
      items:
        $ref: "#/components/schemas/MenuVecInner"
    MenuVecInner:
      type: object
      properties:
        "0":
          type: object
          properties:
            id:
              type: integer
              format: int32
            image:
              type: string
            max_supply:
              type: integer
              format: int32
            name:
              type: string
            price:
              type: number
              format: float
            type:
              type: string
              enum:
                - Soup
                - Main
            week_day:
              type: integer
              format: int32
          required:
            - id
            - image
            - max_supply
            - name
            - price
            - type
            - week_day
        "1":
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
                format: int32
              name:
                type: string
              price:
                type: number
                format: float
            required:
              - id
              - name
              - price
      required:
        - "0"
        - "1"
    UserChangePassword:
      type: object
      properties:
        newPassword:
          type: string
        oldPassword:
          type: string
      required:
        - newPassword
        - oldPassword
    UserLogin:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      required:
        - email
        - password
    UserRegister:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
        username:
          type: string
      required:
        - email
        - password
        - username
paths:
  /api/menu/:
    get:
      responses:
        "200":
          description: OK
          content:
            "*/*":
              schema:
                $ref: "#/components/schemas/MenuVec"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
  "/api/menu/day/{day}":
    get:
      responses:
        "200":
          description: OK
          content:
            "*/*":
              schema:
                $ref: "#/components/schemas/MenuVec"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      parameters:
        - in: path
          name: day
          required: true
          schema:
            type: integer
            format: int32
            pattern: "[0-9]"
  /api/menu/today:
    get:
      responses:
        "200":
          description: OK
          content:
            "*/*":
              schema:
                 $ref: "#/components/schemas/MenuVec"
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
  /api/menu/update:
    get:
      responses:
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
  "/api/menu/{item_id}":
    get:
      responses:
        "418":
          description: TODO
      parameters:
        - in: path
          name: item_id
          required: true
          schema:
            type: integer
            format: int32
  "/api/user/activate/{token}":
    get:
      responses:
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      parameters:
        - in: path
          name: token
          required: true
          schema:
            type: string
  /api/user/change-password:
    post:
      security:
        - UserAuth: []
      responses:
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserChangePassword"
        required: true
  /api/user/delete:
    get:
      responses:
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
  "/api/user/delete/{token}":
    get:
      responses:
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      parameters:
        - in: path
          name: token
          required: true
          schema:
            type: string
  /api/user/get-user-data:
    get:
      responses:
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
  /api/user/login:
    post:
      responses:
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserLogin"
        required: true
  /api/user/register:
    post:
      responses:
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserRegister"
        required: true
info:
  version: ""
  title: ""
