//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.1

use sea_orm::entity::prelude::*;
use serde::Serialize;

use crate::sea_orm_active_enums::ExtrasType;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Hash)]
#[sea_orm(table_name = "extras")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    #[sea_orm(column_type = "Decimal(Some((6, 2)))")]
    pub price: Decimal,
    pub image: String,
    pub r#type: ExtrasType,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::extras_dinner::Entity")]
    ExtrasDinner,
    #[sea_orm(has_many = "super::extras_order::Entity")]
    ExtrasOrder,
}

impl Related<super::extras_dinner::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ExtrasDinner.def()
    }
}

impl Related<super::extras_order::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ExtrasOrder.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
