//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "extras_dinner")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub dinner_id: i32,
    #[sea_orm(unique)]
    pub extras_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::dinner::Entity",
        from = "Column::DinnerId",
        to = "super::dinner::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    Dinner,
    #[sea_orm(
        belongs_to = "super::extras::Entity",
        from = "Column::ExtrasId",
        to = "super::extras::Column::Id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    Extras,
}

impl Related<super::dinner::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Dinner.def()
    }
}

impl Related<super::extras::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Extras.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
