//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.1

pub use super::dinner::Entity as Dinner;
pub use super::dinner_orders::Entity as DinnerOrders;
pub use super::extras::Entity as Extras;
pub use super::extras_dinner::Entity as ExtrasDinner;
pub use super::extras_order::Entity as ExtrasOrder;
pub use super::shop::Entity as Shop;
pub use super::shop_orders::Entity as ShopOrders;
pub use super::user::Entity as User;
pub use super::user_dinner_orders::Entity as UserDinnerOrders;
