//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.1

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "type")]
pub enum Type {
    #[sea_orm(string_value = "soup")]
    Soup,
    #[sea_orm(string_value = "main")]
    Main,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "week_day")]
pub enum WeekDay {
    #[sea_orm(string_value = "monday")]
    Monday,
    #[sea_orm(string_value = "tuesday")]
    Tuesday,
    #[sea_orm(string_value = "wednesday")]
    Wednesday,
    #[sea_orm(string_value = "thursday")]
    Thursday,
    #[sea_orm(string_value = "friday")]
    Friday,
    #[sea_orm(string_value = "saturday")]
    Saturday,
}
